import type { Tenant, User, Task, Lead, Activity, DailyBrief } from '@/types/db';

export const SEED_TENANTS: Tenant[] = [
  {
    id: 't1',
    name: 'By Red LLC',
    type: 'parent',
    color: '#d90009',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 't2',
    name: 'Paradise Property Services',
    type: 'service',
    color: '#0ea5e9',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 't3',
    name: 'HireWire',
    type: 'product',
    color: '#22c55e',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 't4',
    name: 'Authentic Hadith',
    type: 'product',
    color: '#a855f7',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const SEED_USER: User = {
  id: 'u-ro',
  email: 'rorylee@pennenterprisesllc.com',
  name: 'Ro Semeah',
  role: 'admin',
  active: true,
  auth_user_id: null,
  avatar_url: null,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const SEED_TASKS: Task[] = [
  {
    id: 'tk-1',
    tenant_id: 't2',
    monday_item_id: null,
    title: 'Bind GL insurance ($1M/$2M) — Paradise',
    description: 'Contact GL broker and bind the general liability insurance policy for Paradise Property Services. Policy limits: $1M per occurrence, $2M aggregate.',
    due_date: '2026-04-20',
    priority: 'Critical',
    status: 'in_progress',
    estimated_minutes: 90,
    ai_mode: 'AI_ASSIST',
    blocker_flag: false,
    blocker_reason: null,
    blocked_by_task_id: null,
    owner_user_id: 'u-ro',
    revenue_impact_score: 10,
    urgency_score: 10,
    created_at: '2026-04-18T00:00:00Z',
  },
  {
    id: 'tk-2',
    tenant_id: 't2',
    monday_item_id: null,
    title: 'File FBN Paradise Property Services',
    description: 'File the Fictitious Business Name (FBN) statement for Paradise Property Services with the county clerk.',
    due_date: '2026-04-20',
    priority: 'Critical',
    status: 'not_started',
    estimated_minutes: 45,
    ai_mode: 'AI_ASSIST',
    blocker_flag: false,
    blocker_reason: null,
    blocked_by_task_id: null,
    owner_user_id: 'u-ro',
    revenue_impact_score: 9,
    urgency_score: 10,
    created_at: '2026-04-18T00:00:00Z',
  },
  {
    id: 'tk-3',
    tenant_id: 't3',
    monday_item_id: null,
    title: 'Document HireWire data mismatch',
    description: 'Investigate and document the data mismatch issue found in HireWire. Requires direct input from Ro to determine root cause and resolution path.',
    due_date: '2026-04-14',
    priority: 'Critical',
    status: 'overdue',
    estimated_minutes: 30,
    ai_mode: 'HUMAN_ONLY',
    blocker_flag: true,
    blocker_reason: 'Requires Ro input',
    blocked_by_task_id: null,
    owner_user_id: 'u-ro',
    revenue_impact_score: 7,
    urgency_score: 10,
    created_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'tk-4',
    tenant_id: 't1',
    monday_item_id: null,
    title: 'Appoint CA Registered Agent — By Red LLC',
    description: 'Appoint a California registered agent for By Red LLC to handle service of process.',
    due_date: '2026-04-19',
    priority: 'Critical',
    status: 'overdue',
    estimated_minutes: 20,
    ai_mode: 'AI_ASSIST',
    blocker_flag: false,
    blocker_reason: null,
    blocked_by_task_id: null,
    owner_user_id: 'u-ro',
    revenue_impact_score: 6,
    urgency_score: 9,
    created_at: '2026-04-15T00:00:00Z',
  },
  {
    id: 'tk-5',
    tenant_id: 't4',
    monday_item_id: null,
    title: 'Order Authentic Hadith flyers',
    description: 'Design and order promotional flyers for Authentic Hadith product launch.',
    due_date: '2026-05-29',
    priority: 'Medium',
    status: 'not_started',
    estimated_minutes: 15,
    ai_mode: 'AI_EXECUTE',
    blocker_flag: false,
    blocker_reason: null,
    blocked_by_task_id: null,
    owner_user_id: 'u-ro',
    revenue_impact_score: 3,
    urgency_score: 2,
    created_at: '2026-04-18T00:00:00Z',
  },
];

export const SEED_LEADS: Lead[] = [
  {
    id: 'ld-1',
    tenant_id: 't2',
    name: 'Sunrise PM — Balboa Park portfolio',
    phone: '619-555-0191',
    email: 'ops@sunrisepm.example',
    source: 'Yardi referral',
    stage: 'QUALIFIED',
    assigned_user_id: 'u-ro',
    last_contacted_at: '2026-04-18T15:00:00Z',
    next_follow_up_at: '2026-04-21T10:00:00Z',
    revenue_potential: 38400,
    created_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'ld-2',
    tenant_id: 't2',
    name: 'Shoreline Properties — 14 buildings',
    phone: '619-555-0133',
    email: 'lisa@shoreline.example',
    source: 'Cold outreach',
    stage: 'CONTACTED',
    assigned_user_id: 'u-ro',
    last_contacted_at: '2026-04-15T12:00:00Z',
    next_follow_up_at: '2026-04-19T09:00:00Z',
    revenue_potential: 84000,
    created_at: '2026-04-08T00:00:00Z',
  },
  {
    id: 'ld-3',
    tenant_id: 't3',
    name: 'Career coach — bulk HireWire licensing',
    phone: null,
    email: 'coach@example.com',
    source: 'Referral',
    stage: 'QUOTED',
    assigned_user_id: 'u-ro',
    last_contacted_at: '2026-04-17T09:00:00Z',
    next_follow_up_at: '2026-04-22T09:00:00Z',
    revenue_potential: 12000,
    created_at: '2026-04-12T00:00:00Z',
  },
];

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'a-1',
    tenant_id: 't2',
    object_type: 'lead',
    object_id: 'ld-1',
    user_id: 'u-ro',
    type: 'stage_change',
    summary: 'CONTACTED → QUALIFIED',
    created_at: '2026-04-18T15:00:00Z',
  },
  {
    id: 'a-2',
    tenant_id: 't2',
    object_type: 'task',
    object_id: 'tk-1',
    user_id: 'u-ro',
    type: 'lead_link',
    summary: 'Linked to lead ld-1',
    created_at: '2026-04-18T15:01:00Z',
  },
];

export const SEED_DAILY_BRIEF: DailyBrief = {
  id: 'br-1',
  date: '2026-04-20',
  user_id: null,
  summary: {
    headline: '3 due today. GL insurance is the money gate.',
    top_3: [
      'Bind GL insurance',
      'File Paradise FBN',
      'Unblock HireWire data mismatch',
    ],
    warnings: [
      'CA Registered Agent is 1 day overdue — blocks 6 downstream filings.',
    ],
    next_action: 'Call GL broker by 11:00 AM PT.',
  },
  created_at: '2026-04-20T06:00:00Z',
};
